### ISSUE TITLE
Allow to delete a contact from Student Details

### ISSUE THREAD

**Issue by laxsmi** [academico-sis/academico#100]
It is already possible to add (link) a new contact to a student. The contact is recorded in the contacts table in the database. If the student has any contacts, they will display as tabs on the student details view. For instance, [this student has one additional contact](https://ibb.co/tQ9rrKx).

While it is possible to create new contacts, it should also be possible to delete them or at least to remove (detach) them from the student. Currently the trash button (see [screenshot](https://ibb.co/tQ9rrKx)) doesn't do anything. It should perform an AJAX request to delete the contact.

**Comment by Aybee5** [comment]
Hello, I will like to take up this task

**Comment by laxsmi** [comment]
Hi @Aybee5, thanks for your interest in the project. You are welcome to submit a PR for this issue, and you will be credited as a contributor if your PR is accepted. Please let me know if you need any guidance or information to help you with the development process.

**Comment by Aybee5** [comment]
Okay, I'm on it. Do you have anything you can share that will help me in the contribution.

**Comment by laxsmi** [comment]
For now, it's okay to use a <form> to submit a DELETE request to the appropriate route (you should add a `destroy()` method to `ContactController`, add a route to access it, and wrap the existing button within a form to submit the request to this route.

**Comment by mubarak23** [comment]
Let me see if I can come up with something here, what is the route for adding contact

**Comment by laxsmi** [comment]
I suggest you add a route similar to [this one](https://github.com/laxsmi/academico/blob/master/routes/web.php#L67)

**Comment by Aybee5** [comment]
I've added [pull 193](https://github.com/academico-sis/academico/pull/193)

**Comment by laxsmi** [comment]
Hi @Aybee5 and thank you very much for this PR. Unfortunately I am not able to test it - your code looks fine but when I click on the delete button nothing happens. The modal should appear, but it doesn't.

Does everything work on your end?

I have a favor to ask before I can merge your PR: could you rebase your branch on master, re-apply your commit and re-push the PR? Since you merged master into your branch, a lot of files would appear in the merge commit  and I'd prefer to keep the history as clean as possible.

**Comment by laxsmi** [comment]
Fixed by @Aybee5 in #196 and #193

**Comment by laxsmi** [comment]
@all-contributors please add Aybee5 for code
