### ISSUE TITLE
Test Courses features

### ISSUE THREAD

**Issue by thdebay** [academico-sis/academico#177]
We should have tests for the following features:

- [ ] Course creation, list, and relations (model/unit testing)
- [ ] Course scheduling (assign a teacher or a room, change dates, names, coursetimes...)

**Comment by TanoRojas** [comment]
Hello @thdebay! I would like to work on this issue. 
Thanks!

**Comment by thdebay** [comment]
Hi @TanoRojas  and thanks for your interest in the project. Writing more tests would be highly appreciated. A few months ago, I ran the project through [LaravelShift's test generator](https://laravelshift.com/laravel-test-generator) but a lot of them are still incomplete.

Do you need any guidance for this issue? Feel free to ask, I'll try my best to assist you.

Best regards
Thomas

**Comment by thdebay** [comment]
Closed thanks to the work done on PR #223.

@all-contributors add @TanoRojas for code.
