### ISSUE TITLE
Write tests for enrollment-related features

### ISSUE THREAD

**Issue by thdebay** [academico-sis/academico#178]
- [ ] enroll a student in a course
- [ ] view enrollments (authorizations)
- [ ] modify enrollments (change course)

**Comment by AleksandarMitevski** [comment]
Hello, i'd like to try to solve this issue.

**Comment by thdebay** [comment]
Hello @AleksandarMitevski, you are most welcome to work on this feature. Better testing would greatly improve the project quality.

Is there anything you need to get started?

Just out of curiosity, I'd like to know if you are a user of the software, or what your motivations are for contributing to this open-source project?

**Comment by AleksandarMitevski** [comment]
Thanks for the answer@thdebay, i was looking at the EnrollmentTest.php file and saw that the methods 'authorized_users_may_enroll_students' and 'an_enrollment_may_be_changed_by_authorized_users' test whether a student can be enrolled in a course and whether an enrollment can be modified unless i'm mistaken ? 

I'm not a user of this software, i'm a newbie developer still learning PHP and Laravel and i thought i would try to contribute to some open source project to gather a bit of real world experience. I started reading about contributing to open source on GitHub and looked for projects that were using PHP and Laravel and came upon Academico which was interesting and had the good-first-issue label on some issues.

**Comment by thdebay** [comment]
I understand. Writing tests is a great way to improve your PHP/Laravel skills.

You are correct. Some tests are already working, what is needed is to check whether these existing tests actually work and if they cover every possible situation (if they make sense, according to the expected app behaviour).

Also, the test `an_enrollment_may_be_deleted_by_authorized_users_only` is still blank.

**Comment by thdebay** [comment]
Fixed by @AleksandarMitevski in #208
