### ISSUE TITLE
Unable to filter by lead status in Student list

### ISSUE THREAD

**Issue by thdebay** [academico-sis/academico#261]
Because the lead status is a computed property, we cannot filter from CRUD.

**Comment by Dummdevka** [comment]
Hello! Can I work on this issue?

**Comment by thdebay** [comment]
Hello! You are most welcome to work on this issue, and you will be credited as a contributer when your PR is merged. Please feel free to reach out if you need any help or have any questions!

**Comment by Dummdevka** [comment]
I have pulled a request!

**Comment by thdebay** [comment]
Thanks for the PR. Unfortunately, the `getLeadStatusAttribute()` method is not simply a getter for the `lead_status_type_id` property. It returns a _computed_ value that makes it impossible to build the filter based on the database colum. We'd have to run the query first and retrieve all the values, and then filter. Which isn't really compatible with Backpack's filter system...

I guess there are different ways to address this issue, one of them could be to ensure that `lead_status_type_id` is systematically updated whenever the student is enrolled / removed from a course.

If you have other suggestions, please feel free to share them :)

**Comment by Dummdevka** [comment]
What's about listening to ```Enrollments``` events and dynamically update ``` lead_status_type_id ```  ? This way we could implement filter based on database column?

**Comment by thdebay** [comment]
Yes, I think this would work :)

**Comment by Dummdevka** [comment]
Hi! I've just pulled a request!
