### ISSUE TITLE
Prevent dag and drop for unauthorized users

### ISSUE THREAD

**Issue by thdebay** [academico-sis/academico#280]
In the "overview" calendar, drag and drop is always enabled. However, the endpoint is restricted to specific user roles. The front UI should hence prevent unauthorized users from being able to drag-and-drop events

**Comment by pawanrijal** [comment]
Hello, Can I work on this issue

**Comment by thdebay** [comment]
Hello, absolutely, you're welcome to work on this issue! Please let me know if you need anything!

**Comment by pawanrijal** [comment]
authorization is already checked on middleware so cannot view calendar for unauthorized users

**Comment by thdebay** [comment]
Yes, the issue was about restricting the modifications to the ADMIN role, while users with SECRETARY role should be allowed to view but not make any changes
