### ISSUE TITLE
When a new course is created, the start and end date should automatically display the selected period's dates.

### ISSUE THREAD

**Issue by thdebay** [academico-sis/academico#282]
![image](https://user-images.githubusercontent.com/1422621/147390472-24c12182-54ca-4361-a20d-092ecc8bccf6.png)

**Comment by rono516** [comment]
@thdebay  is this issue closed?

**Comment by thdebay** [comment]
The issue was closed when a temporary fix was made. When creating a course, the default start/end dates are initialized to the current period's dates. But of course it would be better to dynamically update the course start/end date fields, when a different period is selected in the "period" form control, and I'll accept a PR that adds this feature
