### ISSUE TITLE
Add emailing features

### ISSUE THREAD

**Issue by thdebay** [academico-sis/academico#283]
- [ ] Allow to send a custom email to all students in a course
- [ ] Allow to send a custom email to "members"
- [x] Allow to send a custom email to a specific student and/or their registered contacts

**Comment by henok-tesfu** [comment]
Hey, i am intersted on this issue can i work on it?

**Comment by thdebay** [comment]
Hello @henok-tesfu and thank you for your interest in the project.

Yes, you're very welcome to work on this feature. I'll assign it to you, please let me know if you need anything!

**Comment by PatrickMamsery** [comment]
Hello @thdebay I am very interested in this issue. May I work on it too?

**Comment by thdebay** [comment]
Hello @PatrickMamsery I didn't have news from @henok-tesfu so I'll assign the issue to you if you want to work on this feature.

Is it clear where to start? Please let me know if you need guidance

**Comment by PatrickMamsery** [comment]
Thanks @thdebay for the opportunity. I am currently working on my local environment setup so that I can run it successfully using Docker. I'll sure notify you in case of anything.

**Comment by wyntonfranklin** [comment]
hey is this still open if not I would like to work on it. Did you have any idea how you'd like it done?

**Comment by thdebay** [comment]
Hello @wyntonfranklin, I did not receive PRs from the other developers so I guess the issue is still open. I think a good way to start would be to implement an email feature allowing to write a message to an individual student. You can create a new page with a form to write the email, and the logic to send it to the email registered in the student profile.

Once we have that, it will be easier to implement more complex features such as grouped emailing (for a whole class).

What do you think?

**Comment by wyntonfranklin** [comment]
Sure, that sounds good for a start. I'll get working on it.

**Comment by wyntonfranklin** [comment]
Hi @thdebay. I created an email controller page and added the email sending logic. For some reason the redirect after sending the email is not working all the time. (not sure why yet) the branch is [here](https://github.com/wyntonfranklin/academico/tree/email-features).

What's next?

<img width="965" alt="Screenshot_1_of_email_page" src="https://user-images.githubusercontent.com/30404746/209873534-bc33ca99-8ece-4525-84b8-bd5dd3742fdc.png">

**Comment by thdebay** [comment]
Hello @wyntonfranklin, thank you for your message. It looks great! Can you open a merge request so that I can make a few comments on your code?

The redirect should work, but I'll test it on my local machine and let you know.

I think the next steps would be:
- to add an "Write an email" button in the student details view, that would redirect to the page you made.
- to add a similar button in the course "show" view (the list of students) to allow to send the email to the whole class.

What do you think?

**Comment by wyntonfranklin** [comment]
hi @thdebay thanks. I will do the merge request. I can start looking at the other steps as well.

**Comment by wyntonfranklin** [comment]
@thdebay, wondering about leadtypes in the students/show.blade.php shows as undefined. might that be an error or did I do something wrong. I usually uncomment the component to interact with this page.

**Comment by thdebay** [comment]
This feature has been removed, I updated the `students/show.blade.php` code to get rid of the legacy component. Please let me know if it fixes the error!

**Comment by wyntonfranklin** [comment]
it works

**Comment by wyntonfranklin** [comment]
Wondering which is the preferred button location for email to student button?
<img width="933" alt="Screenshot_email_ui" src="https://user-images.githubusercontent.com/30404746/211192822-5b5285bc-d16e-4ce1-8d3b-22c1e16dafc7.png">

**Comment by thdebay** [comment]
I think next to the "edit" button is better, but I'm also open to your suggestions. I think it integrates better into the UI. What do you think?

**Comment by wyntonfranklin** [comment]
I agree. I left it next to the edit button. Initially I didn't quite understand how to place a button there so placing at the top was simplest.

**Comment by thdebay** [comment]
Fixed in #312
