### ISSUE TITLE
Add stats for students' ages

### ISSUE THREAD

**Issue by thdebay** [academico-sis/academico#286]
Display the number of students in each age category:

- 0-6 years old
-7-12 years old
- 8-14 years old
- 15-20 years old
- 21 years old and +

Ideally, make these categories configurable (in a config file or DB entry in the Config table).

**Comment by Dummdevka** [comment]
Hello! Can I work on this issue?

**Comment by thdebay** [comment]
Hello @Dummdevka ! Yes, you're very welcome to work on this feature. You can see how charts are built in the [latest views](https://github.com/academico-sis/academico/blob/master/resources/views/reports/gender.blade.php) and reproduce something similar (the <script> tags will be migrated to a full Webpack integration someday), or you may also built them in your own preferred way, that's okay. There are lots of options, such as `consoletvs/charts` or the vue integration plugin for Chart.js. Feel free to suggest what you think is best :)

Please let me know if you need anything, and I'd be glad to help you discuss your ideas if needed.

**Comment by rm-yakovenko** [comment]
Hello @Dummdevka! Are you still looking into it? 

I have a couple of ideas and want to check if they will work.

**Comment by DamoFD** [comment]
Still need this feature added?

**Comment by thdebay** [comment]
Yes @DamoFD  the feature is still in demand and you are welcome to work on it if you wish!

**Comment by DamoFD** [comment]
@thdebay awesome! I'll get to work on it, I'll PR in a few days 👍

**Comment by rono516** [comment]
> @thdebay awesome! I'll get to work on it, I'll PR in a few days 👍

I'd love to work on this. Updates on the PR?

**Comment by thdebay** [comment]
I didn't receive any pr for this issue, you're welcome to submit one of you're interested

**Comment by rono516** [comment]
I'm working on it @thdebay . I'll submit a PR once I'm done.

**Comment by rono516** [comment]
> I didn't receive any pr for this issue, you're welcome to submit one of you're interested

Hello @thdebay I added a  [pull request](https://github.com/academico-sis/academico/pull/323) aiming to add this feature. I have added necessary description and I hope I get feedback.

**Comment by thdebay** [comment]
@all-contributors add @rono516 for code
