### ISSUE TITLE
Database is not filled correctly

### ISSUE THREAD

**Issue by Sempro97** [academico-sis/academico#310]
Hi! I was tring to compile the project but an error occurred when i try to execute "php artisan db:seed"

## Expected Behavior
The command execute without errors

## Current Behavior
Here the result of the command https://pastebin.com/NP1CgpTk

## Possible Solution
I found a person with the same problem that solved using json_encode(), maybe it could be solving:
[Here](https://stackoverflow.com/questions/62849264/laravel-return-array-to-string-conversion-error)

## Steps to Reproduce
Follow the guide of first installation until "php artisan db:seed"

## Context (Environment)
MySQL:8.0.30 ([docker-compose.yaml](https://pastebin.com/4RWHdyeQ))
Php: PHP 8.1.11 with [PHP Modules]:
```
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
json
libxml
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

Anyone have some feedback? 
Thanks in advice.

**Comment by thdebay** [comment]
Hello @Sempro97,

I checked and there was indeed a faulty seeder that blocked the process. It's fixed now. Thanks for reporting this bug 👍🏻
